### ISSUE TITLE
Implementation of Training Trader Robots Using Deep Reinforcement Learning for Live Trading

### ISSUE THREAD

**Issue by waudinio27** [PacktPublishing/Hands-On-Deep-Learning-for-Finance#15]
Dear  Hands-On-Deep-Learning-for-Finance authors!

I wanted to say a big Thank you to all of you. In my eyes, this book is really the best. Very comprehensive and good to follow for beginners.

I want to implement the RL Bot for live trading on my Demo Account to test it for real.

Therefor I have one question:

Is there a need to transform and prepare the OHLC candles from a live stream before it is possible to make the actual predictions? 
Like in

def prepare_dataset(close):

or 

Is it possible to just take the raw data and make predictions with the model? 

Thanks a lot again and keep up the great work,

Matthias

**Comment by abhandari73** [comment]
Hi Mathias,

Thank you for your kind words.

The prepare_dataset function is used for the specific transformation i.e. technical indicators that are fed to the system while training. When running the live model, dataset would need to be prepared in the same way to be useful for prediction.

If you are planning to use a raw series (OHLC) rather than some transformation, then you need to determine what the signal values are going to be. Inputting a raw series without some factor of time dependence is unlikely to yield any result. 

In production, when the model is run on live data, the preprocessed will take care of input parameters in form used by the model.


Trust this helps.

May I ask you if you purchased the book from amazon / packt.


Kind Regards,
Arjun Bhandari
+97150 780 5672

**Comment by waudinio27** [comment]
Hello Arjun, 

Thanks a lot for your fast and comprehensive reply. I appreciate this a lot. 

So far I have read the book in the 10-day free trial:

https://subscribe.packtpub.com/free-trial/

I want to obtain a hard copy soon on Amazon and write a recommendation there. 

Greetings 

Matthias

**Comment by waudinio27** [comment]
> 
> 
> Hello Arjun,
> 
> Thanks a lot for your fast and comprehensive reply. I appreciate this a lot.
> 
> So far I have read the book in the 10-day free trial:
> 
> https://subscribe.packtpub.com/free-trial/
> 
> I want to obtain a hard copy soon on Amazon and write a recommendation there.
> 
> Greetings
> 
> Matthias

**Comment by waudinio27** [comment]
Hello Arjun,

I wanted to add one more comment. 
It is really great that this RL-Bot is able to open Long and Short positions. 

Thanks again and kind regards,

Matthias
