### ISSUE TITLE
The Repo is Really not downloadable - tried all methods

### ISSUE THREAD

**Issue by rohan-paul** [PacktPublishing/Hands-On-Deep-Learning-for-Finance#16]
Could not download the repo in any way. Tried all possible methods. Not working in Linux and Windows.

Dont know why you guys are not using a G-Drive for all the 9GB or more data.

And its also mentioned in the Book's Amazon Reviews and people have given lower stars for this reason.

**Comment by abhandari73** [comment]
Hi Rohan,

Packt is not supporting the book for the past few months. I am not sure if the repo is online or not. They have withdrawn the book so should not be available on their catalogue as well.


Kind Regards,
Arjun Bhandari
+97150 780 5672

**Comment by Sinansi** [comment]
Packt have also withdrawn Hands-On Python for Finance by Krish Naik. I am not sure why they drop many books!

Rohan made a good suggestion. Why not share the repo on Google Drive? It should be free since it is less than 15GB. Create a Google Drive with the book name and paste the link on the repo home page.

Additionally, Hands-On Deep Learning for Finance is a great book. Unlike other ML trading books which duplicate many topics (Copy & Paste from each other), Hands-On DL for Finance has unique topics not available in other books. 

I would love to see a second edition for this book, updated to TensorFlow 2.

**Comment by gaurav-packt** [comment]
Hello,

The book has been removed from sale however, I'm still able to download the code files through **Code** | **Download ZIP**. 

Can you please check and verify?

**Comment by Sinansi** [comment]
Yes, the file is downloadable. I have downloaded it about 5 times, but every time I try to unzip it, I get the following error:

C:\Users\sinan\Desktop\New folder\Hands-On-Deep-Learning-for-Finance-master.zip: The archive is corrupt!

I opened the zipped file in WinRAR and chose repair (rebuild) file. I was able to unzip the rebuilt successfully.
